### ISSUE TITLE
Mobi file can't parse

### ISSUE THREAD

**Issue by LiuDeng** [bfabiszewski/libmobi#10]
Mobi parse failed but can be open in Kindle app.
File is in attachment.
Thank you for your great work~
Best Regards.
[World of Warcraft - Dawn of the Aspects Part I.mobi.zip](https://github.com/bfabiszewski/libmobi/files/1867588/World.of.Warcraft.-.Dawn.of.the.Aspects.Part.I.mobi.zip)

**Comment by LiuDeng** [comment]
Thank you so much！！！ 
Best Regards！！！

**Comment by gregko** [comment]
I tested the "World of Warcraft - Dawn of the Aspects Part I.mobi" file as well, it works much better after the latest fixes, thank you. However the toc.ncx that libmobi generates from this file has wrong links. For example for "Part I" we have in toc.ncx:

  &lt;navPoint id="toc-3" playOrder="3"&gt;
   &lt;navLabel&gt;
    &lt;text>Part I</text&gt;
   &lt;/navLabel&gt;
   &lt;content src="part00000.html#0000006908"/&gt;

However, there is no element with id "0000006908" in part00000.html at all. Instead, "Part I" header is preceded with:

&lt;a id="0000006902"&gt;

Could you maybe tell me where and how the toc.ncx is constructed, maybe then I could find a fix on my own...

Greg

**Comment by bfabiszewski** [comment]
@gregko 
I looked at it and it seems to be unrelated to this bug. I'll prepare a fix. 
In the meantime, could you create a new issue for that?

**Comment by gregko** [comment]
Thank you, created new issue #12
