### ISSUE TITLE
Mobi file can't parse.

### ISSUE THREAD

**Issue by LiuDeng** [bfabiszewski/libmobi#11]
Thank you and sorry to trouble you aging.
Best Regards.

[pg1342-images.mobi.zip](https://github.com/bfabiszewski/libmobi/files/1872471/pg1342-images.mobi.zip)

**Comment by bfabiszewski** [comment]
What is the problem with this file?
I tried and It opens and parses without problems.
This file doesn't contain any images.

**Comment by LiuDeng** [comment]
I am so so sorry. It is my fault~
Best Wishes~
