### ISSUE TITLE
toc.ncx is sometimes created with wrong navigation labels

### ISSUE THREAD

**Issue by gregko** [bfabiszewski/libmobi#12]
The issue is with "World of Warcraft - Dawn of the Aspects Part I.mobi" ebook file, submitted with "Mobi file can't parse #10" by @LiuDeng:

The toc.ncx that libmobi generates from this file has wrong links. For example for "Part I" we have in toc.ncx:

  &lt;navPoint id="toc-3" playOrder="3"&gt;
   &lt;navLabel&gt;
    &lt;text>Part I</text&gt;
   &lt;/navLabel&gt;
   &lt;content src="part00000.html#0000006908"/&gt;

However, there is no element with id "0000006908" in part00000.html at all. Instead, "Part I" header is preceded with:

&lt;a id="0000006902"&gt;

Could you maybe tell me where and how the toc.ncx is constructed, maybe then I could find a fix on my own...

Greg

**Comment by bfabiszewski** [comment]
I pushed a fix. I looks as it was broken long time ago.
I hope it will work now as expected.

**Comment by gregko** [comment]
Thank you, Bartek, works great now! I appreciate very much all your great support and effort to maintain this valuable library.

Greg
