### ISSUE TITLE
mobitool -d <file> -o <output directory> ignores -o argument

### ISSUE THREAD

**Issue by philgoetz** [bfabiszewski/libmobi#13]
```
$ mobitool.exe -d data/googled.mobi -o .
Title: Googled
Author: Ken Auletta
. . . <output snipped> . . .

Dumping rawml...
Saving rawml to data/googled.rawml
```

**Comment by bfabiszewski** [comment]
The syntax of your command is wrong. Path to mobi file must be last argument:
`usage: mobitool [-deimrsuvx7] [-o dir] [-p pid] [-P serial] filename`

In your case `mobitool.exe -d -o . data/googled.mobi` should work.

**Comment by philgoetz** [comment]
Oops! That works. Thanks!
