### ISSUE TITLE
Can't get image from mobi

### ISSUE THREAD

**Issue by LiuDeng** [bfabiszewski/libmobi#14]
Hello @bfabiszewski 
I am using your another lib QLMobi combine with libmobi to parse html and images from mobi book.
Most book works great, but some books can not get media image.
I have try to fix but can not get the point. Hope you can help,this is the last problem for me i think~
Both QLMobi and libmobi are great nearly perfect lib.
Thank you very much for your great job~
[World of Warcraft - Dawn of the Aspects Part I.mobi.zip](https://github.com/bfabiszewski/libmobi/files/1917987/World.of.Warcraft.-.Dawn.of.the.Aspects.Part.I.mobi.zip)

Also i am the developer of Alook Browser - 2x Speed (https://itunes.apple.com/us/app/alook-web-browser-2x-speed/id1261944766?mt=8)  if you are using iOS ，and here is a  promotional code JWYTH3FE4JJK 
Forgive my poor english~
Best Regards.

**Comment by LiuDeng** [comment]
Here is the debug info. the media is nil.
![medianil](https://user-images.githubusercontent.com/1720312/38846234-e892346a-422d-11e8-92f1-4e3ffa463892.png)

**Comment by bfabiszewski** [comment]
I compared reconstructed book with Kindle.app and I don't see any image missing. Maybe there is some image link that is broken, that's why you get `nil` value for media object.
Can you see any image in Kindle.app that is missing from libmobi output?

**Comment by bfabiszewski** [comment]
By the way.

Some time ago I found out you are using code of two of my projects in Alook browser: QLMobi and Libmobi. They are licensed with GPL and LGPL respectively. 
Regarding GPL, you can use it as long as you project is also GPL. You would have to publish the source code of Alook browser in such case.
Regarding LGPL, you can use it in non-GPL projects, you will just have to comply with the license terms. You should find out how to do it for you platform. If you make any changes to library code you should make the changes available, you should include the copyright info in your project.

Please make sure you are not breaking any rules.

Here Alook disassembly shows QLMobi methods:

![alook](https://user-images.githubusercontent.com/3366666/38853184-b96ccc7e-421c-11e8-8af5-c271aefe8717.png)

**Comment by LiuDeng** [comment]
@bfabiszewski I am sorry that i am using the QLMobi and libmobi. I use the libmobi and not change any code, i just submit issue. Sorry for i don't find QLMobi is GPL.  Forgive me, and I will soon rewrite the code  or remove it from the project.
Best regards.

**Comment by LiuDeng** [comment]
@bfabiszewski  By the way, can you please change the QLMobi to LGPL?
I will be so appreciate for that.

**Comment by LiuDeng** [comment]
@bfabiszewski  for this issue, i can get no image from libmobi output the media is always nil in the loop.

**Comment by LiuDeng** [comment]
For example, bellow image is not parsed.
![noimage](https://user-images.githubusercontent.com/1720312/38883888-b6da82c4-42a0-11e8-9508-dea6e5b6ff0b.png)

**Comment by bfabiszewski** [comment]
I can see the image in QLMobi output

![ww](https://user-images.githubusercontent.com/3366666/38913285-33c7cb6e-42da-11e8-8f01-7b172f52be4b.png)

**Comment by LiuDeng** [comment]
It seems to be my problem. Let me debug again.
If you won't change QLMobi to LGPL i will try to rewrite it in swift.
Anyway, thank you for your great work!~ And best wishes~

**Comment by bfabiszewski** [comment]
I don't want to change licences. Please respect it and make fair use of my work.

**Comment by LiuDeng** [comment]
I have been working on this those days and have rewrited QLMobi related codes to Swift ，you can check it next version.
Thank you.
Best Regards.
