### ISSUE TITLE
How to get the HTML content with the specified sequence number as fast as possible?

### ISSUE THREAD

**Issue by csshuai** [bfabiszewski/libmobi#15]
When i parse big file. Method `MOBI_RET mobi_parse_rawml(MOBIRawml *rawml, const MOBIData *m)` is too slow.

How to get the HTML content with the specified sequence number as fast as possible?

**Comment by bfabiszewski** [comment]
You may try to use [mobi_parse_rawml_opt](https://github.com/bfabiszewski/libmobi/blob/0e8e8357e258477f5a7523e2a0a68d1ffb6cfd0d/src/parse_rawml.c#L1969) function. It will let you skip some parsing steps if you don't need those.
