### ISSUE TITLE
Can't convent pdb files to epub

### ISSUE THREAD

**Issue by foobnix** [bfabiszewski/libmobi#20]
Please check I can't convert that pdb to epub
"Error while loading document (Unsupported document format)"
[PDB.zip](https://github.com/bfabiszewski/libmobi/files/2639174/PDB.zip)

**Comment by bfabiszewski** [comment]
Thanks for the report.
Not all `pdb` files are supported by the library. Generally Palm database (`pdb`) is a carrier for different document types, of which Libmobi should handle PalmDoc, MobiPocket, TealDoc. The other variations, in your case Silo or FireViewer, differ from popular `mobi` format and will not be supported.
