### ISSUE TITLE
I am confused about a function.

### ISSUE THREAD

**Issue by buzai** [bfabiszewski/libmobi#22]
_buffer_get_varlen I am puzzled by this function, why should I read 7 bit, Stops when byte has bit 7 set, I am also confused about this condition. Should not be a step-by-step read 8 bit

**Comment by bfabiszewski** [comment]
I believe this is how some data is encoded in mobi format.
Do you encounter any problem with this function? Any example where it doesn't work?

**Comment by buzai** [comment]
@bfabiszewski Thank u, I am just confused. If this is the format requested by mobi, I will understand it.
