### ISSUE TITLE
README question: can libmobi also create new documents from scratch?

### ISSUE THREAD

**Issue by ghost** [bfabiszewski/libmobi#25]
The README lists a lot of features, but they're all apparently centered around reading or *modifying* an existing file.

Can libmobi also create new ebooks from scratch? (For use in an EPUB->MOBI conversion software) If yes, maybe another bullet point in the README clarifying that would be useful :slightly_smiling_face: 

Thanks for creating this cool library!

**Comment by bfabiszewski** [comment]
Currently only reading, parsing and modifying metadata is supported.
Creating from scratch is not possible.

**Comment by ghost** [comment]
@bfabiszewski thanks for the quick answer, very appreciated! curious, is this on the roadmap somewhere down the line? right now I'm using calibre's ebook-convert but it can't be installed standalone but only as part of a huge program, and I'd rather use a library if I can find any. So I'd be very interested in this :slightly_smiling_face:

**Comment by bfabiszewski** [comment]
I would like to implement it some day, but I need to find more time.
This is a bit complicated. Can't promise it will be soon. :)
