### ISSUE TITLE
tarball is missing for latest releases (e.g. 0.6)

### ISSUE THREAD

**Issue by avsej** [bfabiszewski/libmobi#28]
Github-provided tarballs are pretty bad, because the size is about 45 megabytes

**Comment by bfabiszewski** [comment]
I added tarball.
You can also create it yourself by running `make dist`.
The size is large because of test samples. Feel free to remove samples if you want even smaller tarball.

**Comment by avsej** [comment]
Thanks, Bartek.

I know about `make dist`, but it creates different tarball every time (I mean because of timestamps and such, hash sum of the tarball is changes). So it is great when there is "official" publicly available tarball to refer in packaging scripts (like this one https://src.fedoraproject.org/rpms/libmobi).

**Comment by bfabiszewski** [comment]
Ok. Now I see. I couldn't understand why you need it.
Thanks for maintaining Fedora package!
