### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [bfabiszewski/libmobi#34]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by occia** [comment]
This issue is related with the recent [PR](https://github.com/bfabiszewski/libmobi/pull/33) I created

**Comment by occia** [comment]
The proposed [PR](https://github.com/bfabiszewski/libmobi/pull/33) has been accepted, I think it is safe to close this.

**Comment by occia** [comment]
@bfabiszewski hi, i recently proposed 4 security issues in here, and also submitted them in huntr.dev for bounties. Would you mind to add the Security.md they mentioned before or do sth else to communicate with them (for this way, I can proceed the process in their websites). Thank you very much~

**Comment by bfabiszewski** [comment]
Hi, I have already created global security policy according to Github guidelance (https://github.com/bfabiszewski/.github/commit/760ddba2e2c9e0eab376a0bdab4463af37e5aab0).

**Comment by occia** [comment]
Hi, may you access this [link](https://www.huntr.dev/bounties/fcb4383c-bc27-4b89-bfce-6b041f0cb769/), and confirm that the oob write bug is confirmed and fixed? thanks! In that page, you may see sth like _**If you're the maintainer, login to view the report**_.
And I'll put all bug details in these links next time (including the three currently pending issues) for a better bug submission process!
