### ISSUE TITLE
Another Out-of-bound read vulnerability caused by incomplete check inside `mobi_decompress_huffman_internal`

### ISSUE THREAD

**Issue by occia** [bfabiszewski/libmobi#36]
Detail bug report is at [here](https://www.huntr.dev/bounties/540fd115-7de4-4e19-a918-5ee61f5157c1/). Developer can access it by logging in.

**Comment by occia** [comment]
I proposed a quick fix in #37

**Comment by bfabiszewski** [comment]
Closed by https://github.com/bfabiszewski/libmobi/commit/bec783e6212439a335ba6e8df7ab8ed610ca9a21
