### ISSUE TITLE
Use Out-of-Range-Pointer-Offset for `huffcdic->symbols` and `huffcdic->symbols[xx]`

### ISSUE THREAD

**Issue by occia** [bfabiszewski/libmobi#38]
Developers of this repo can access bug details at [here](https://www.huntr.dev/bounties/722b3acb-792b-4429-a98d-bb80efb8938d/).

**Comment by bfabiszewski** [comment]
Thanks. I am busy now. I get back to the issues as soon as I find some free time.
Same applies to #35 and #36.

**Comment by occia** [comment]
@bfabiszewski hi, I'm currently applying cves for these bugs and the application process in huntr involves the developer, may you go back to huntr website (from the reports link [1](https://www.huntr.dev/bounties/722b3acb-792b-4429-a98d-bb80efb8938d/) [2](https://www.huntr.dev/bounties/efb3e261-3f7d-4a45-8114-e0ace6b21516/) [3](https://www.huntr.dev/bounties/540fd115-7de4-4e19-a918-5ee61f5157c1/)) and comment on the cve application process in there? Thanks~
