### ISSUE TITLE
convert azw3 ebook to epub error

### ISSUE THREAD

**Issue by forkdog** [bfabiszewski/libmobi#42]
printf("Could not initialize zip archive\n");
Here is the link to the file I tested. 
https://1drv.ms/u/s!AkaVccfysLmAhI5Odqj2pZ1QCMci6g?e=U9lkC3

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h0z4bfdgh7j20io0fdmz0.jpg)

**Comment by bfabiszewski** [comment]
Hi,
I can't reproduce it.
It works with libmobi 0.10 on Linux:

```
mobitool -e test.azw3
Title: 航海王/One Piece/海贼王（第1部：卷1~卷8） (经典珍藏版，一场追逐自由与梦想的伟大航程，一部诠释友情与信念的热血史诗！全球发行量超过4亿7000万本，吉尼斯世界记录保持者！)
Author: 尾田荣一郎
Publishing date: 2020-06-01
ASIN: B089CHYG8J
Language: zh (utf8)
__
Mobi version: 8
Creator software: kindlegen 2.9.0 (linux)

Reconstructing source resources...

Creating EPUB...
Saving EPUB to test.epub
```

I suppose there is something wrong with the output folder. Make sure the output folder exists and is writable.

If you still have problems, please give more details: libmobi version, OS, configure options.

**Comment by forkdog** [comment]
Thank you very much. I have solved it because of my directory path problem, because I use this title as the file name to write, but this title contains "/".
