### ISSUE TITLE
[RFE] support epub format

### ISSUE THREAD

**Issue by grexe** [bfabiszewski/libmobi#48]
Would it be out of scope to add epub support? (yes I know the name would have to be changed properly...;-)
I couldn't find a current C library that does the same for epub files, and this library could become the unified solution for ebook formats.

**Comment by bfabiszewski** [comment]
Sorry, it won't fit here. Completely different format.
Epub files are just zip containers with a bunch of html files plus some css, images. You should look for tools that can handle web content.

**Comment by grexe** [comment]
Ok thanks, thought so. 
Only found [libepub](https://github.com/artemisfowl/libepub) so far, which seems not finished and pretty old, I'll give it a try. 
If you know any better/more current lib I'd be really grateful.

**Comment by bfabiszewski** [comment]
To create epub file I am using libxml2 for markup and miniz for zip compression.
