### ISSUE TITLE
MOBI_ATTRNAME_MAXSIZE 100 for some books it's not enought

### ISSUE THREAD

**Issue by foobnix** [bfabiszewski/libmobi#5]
Please increase MOBI_ATTRNAME_MAXSIZE and  MOBI_ATTRVALUE_MAXSIZE to 150

#define MOBI_ATTRNAME_MAXSIZE 150 /**< Maximum length of tag attribute name, like "href" */
#define MOBI_ATTRVALUE_MAXSIZE 150 /**< Maximum length of tag attribute value */

thanks

**Comment by bfabiszewski** [comment]
Thanks for the feedback!
I'll correct the max values according to your suggestion.

I noticed you use libmobi in your project. 
If you don't mind I will add Librera Reader to "[Projects using libmobi](https://github.com/bfabiszewski/libmobi#projects-using-libmobi)" section in README.

**Comment by foobnix** [comment]
Thank you for the libmobi, it's very good for converting Kindle formats to epub. Yes, you can add Librera to the README.
