### ISSUE TITLE
Amazon azw4 format?

### ISSUE THREAD

**Issue by gregko** [bfabiszewski/libmobi#8]
Cześć Bartek!
One of the users of my app (@Voice Aloud Reader in Google Play) sent me the first azw4 ebook. Do you think you could include this format into your library? Would you need any help with this? I was able to convert the file to epub using the latest calibre, but the format is weird - short lines about 80 characters long formatted as &lt;p&gt;...&lt;/p&gt;. Could be a problem with this original file, or calibre's conversion process, don't know at this time.

OK, just managed to update my old Kindle HDX 3rd generation, and it opened the azw4 file fine, no problem with formatting there. Apparently Calibre's conversion is not perfect yet. Please let me know if you have any plans regarding AZW4. Thanks!

Grzesiek

**Comment by gregko** [comment]
Darn, I should better keep up with your updates, I see in README now that "Replica Print files (azw4)" is already supported. Must pull your sources again see what happens with that ebook I got, when converted through it. Thanks!

**Comment by bfabiszewski** [comment]
Cześć!

Libmobi handles azw4 files. Technically these are pdf files embedded in mobi container.
LIbmobi will let you access the pdf, but this format is not conversion friendly and beyond the scope of libmobi. You will have to further process it in your application.

The other problem I can see is that azw4 files are often encrypted.

Pozdrowienia!
Bartek

PS. From your second mail I can see you already know everything. :)

**Comment by gregko** [comment]
Tak, dokopałem się w Twoim kodzie źródłowym. Z PDF sobie radzę, ale życzę jego twórcom aby smażyli się w piekle na wieki J Zaszyfrowane pliki to inna sprawa, ja tego nigdzie nie polecam, ale nadmieniam jak się ktoś pyta, że są nieoficjalne sposoby usuwania DRM. Wielu użytkowników je sobie znajduje. Trzymaj się dzielnie i życzę samych sukcesów. Jeśli masz ochotę to napisz co ciekawego robisz ostatnio.

 

Ja np. przez cały weekend prawie walczyłem z PDFami, sformatowanymi tak że tekst jest w złej kolejności, np. prawa kolumna przed lewą i gorzej. Automatycznie to znanalizować i przetworzyć na poprawną kolejność jest bardzo trudno, więc musiałem zastosować największą armatę w naszym arsenale: HI. Jak chesz to zerknij na: http://hyperionics.com/atVoice/PdfPluginHelp.html#complex

 

 

Grzegorz
