### ISSUE TITLE
Mobi parse failed but can be open in Kindle app.

### ISSUE THREAD

**Issue by LiuDeng** [bfabiszewski/libmobi#9]
Mobi parse failed but can be open in Kindle app.
File is in attachment.
[请停止无效努力.mobi.zip](https://github.com/bfabiszewski/libmobi/files/1779442/mobi.zip)

Thank you for your great work~
Best Regards.

**Comment by bfabiszewski** [comment]
Thanks for the report!

The problem with the file is probably caused by third party software used to create it (epubor). It creates zero length text record. I fixed it by skipping such corrupt record instead of exiting with error status.

**Comment by LiuDeng** [comment]
@bfabiszewski Thank you so much!
Best wishes~
------------------------------------------
And i have a mobi file that Kindle app get parse its image while libmobi can't. I saw the you replace the empty image with empty gif in QLMobi project. Is there any way to fix this?
[zero to one.mobi.zip](https://github.com/bfabiszewski/libmobi/files/1783138/zero.to.one.mobi.zip)

**Comment by bfabiszewski** [comment]
What is the problem with this file? 
In case of QLMobi, if there are missing images in original layout I replace them with empty gif. But this is not the role of the libmobi. Libmobi only reconstructs ebook source files, it doesn't fix any problems in original source.

**Comment by LiuDeng** [comment]
the problem is it can not get image or lose image while reconstructs from this file。Kindle app can show the image~
Thank you~

**Comment by bfabiszewski** [comment]
Which image? I don't see any images missing in mobitool output.
